CREATE TABLE Gym
(
	GymId SMALLINT IDENTITY(1, 1) NOT NULL
	, CompanyId SMALLINT NOT NULL
	, Name VARCHAR(100) NOT NULL
	, CONSTRAINT PK_Gym PRIMARY KEY (GymId)
	, CONSTRAINT FK_Gym_Company FOREIGN KEY (CompanyId) REFERENCES Company (CompanyId)
)
